FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY StudentRecordManagement.Web.csproj ./
RUN dotnet restore StudentRecordManagement.Web.csproj

COPY . .

RUN dotnet publish StudentRecordManagement.Web.csproj \
    -c Release \
    --no-restore \
    -o /app/publish \
    /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble-chiseled AS final

WORKDIR /app

COPY --from=build /app/publish ./

ENV PORT=8080
ENV DOTNET_EnableDiagnostics=0

ENTRYPOINT ["dotnet", "StudentRecordManagement.Web.dll"]